name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Clean Install dependencies and Build
        run: |
          yarn install
          rm -rf build
          yarn build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build

      - name: Run Jest
        uses: stefanoeb/jest-action@1.0.3
